-- phpMyAdmin SQL Dump
-- version 4.2.5
-- http://www.phpmyadmin.net
--
-- Host: localhost
-- Generation Time: Nov 22, 2014 at 04:58 PM
-- Server version: 5.5.40-0ubuntu0.14.04.1
-- PHP Version: 5.5.9-1ubuntu4.5

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;

--
-- Database: `c1dev3`
--

-- --------------------------------------------------------

--
-- Table structure for table `company`
--

CREATE TABLE IF NOT EXISTS `company` (
`ID` int(11) NOT NULL,
  `Company` varchar(255) DEFAULT NULL,
  `ELDate` varchar(255) DEFAULT NULL,
  `IBCDate` varchar(255) DEFAULT NULL,
  `EstCloseDate` varchar(255) DEFAULT NULL,
  `ProjectName` varchar(255) DEFAULT NULL,
  `ELExpirationDate` varchar(255) DEFAULT NULL,
  `Status` varchar(255) DEFAULT NULL,
  `DealType` varchar(255) DEFAULT NULL,
  `DealSlot` varchar(255) DEFAULT NULL,
  `ClosedDate` varchar(255) DEFAULT NULL,
  `DeadDate` varchar(255) DEFAULT NULL,
  `PrimaryBanker` varchar(255) DEFAULT NULL,
  `PracticeArea` varchar(255) DEFAULT NULL,
  `Industry` varchar(255) DEFAULT NULL,
  `ProjectedTransactionSize` varchar(255) DEFAULT NULL,
  `EnterpiseValue` varchar(255) DEFAULT NULL,
  `FinalTransactionSize` varchar(255) DEFAULT NULL,
  `ProjectedFee` varchar(255) DEFAULT NULL,
  `FeeMinimum` varchar(255) DEFAULT NULL,
  `EngagmentFee` varchar(255) DEFAULT NULL,
  `FeeDetails` varchar(255) DEFAULT NULL,
  `SplitToCorporate` varchar(255) DEFAULT NULL,
  `MonthlyRetainer` varchar(255) DEFAULT NULL,
  `FinalTotalSucessFee` varchar(255) DEFAULT NULL,
  `OwnershipClass` varchar(255) DEFAULT NULL,
  `ReferralType` varchar(255) DEFAULT NULL,
  `ReferralSourceCompany` varchar(255) DEFAULT NULL,
  `ReferralScourceInd` varchar(255) NOT NULL,
  `Description` varchar(255) DEFAULT NULL,
  `TeamSplit1` varchar(255) DEFAULT NULL,
  `Team1` varchar(255) DEFAULT NULL,
  `TeamSplit2` varchar(255) DEFAULT NULL,
  `Team2` varchar(255) DEFAULT NULL,
  `TeamSplit3` varchar(255) DEFAULT NULL,
  `Team3` varchar(255) DEFAULT NULL,
  `TeamSplit4` varchar(255) DEFAULT NULL,
  `Team4` varchar(255) DEFAULT NULL,
  `TeamSplit5` varchar(255) DEFAULT NULL,
  `Team5` varchar(255) DEFAULT NULL,
  `TeamSplit6` varchar(255) DEFAULT NULL,
  `Team6` varchar(255) DEFAULT NULL,
  `FeeSplit1` varchar(255) DEFAULT NULL,
  `FeeTo1` varchar(255) DEFAULT NULL,
  `FeeSplit2` varchar(255) DEFAULT NULL,
  `FeeTo2` varchar(255) DEFAULT NULL,
  `FeeSplit3` varchar(255) DEFAULT NULL,
  `FeeTo3` varchar(255) DEFAULT NULL,
  `FeeSplit4` varchar(255) DEFAULT NULL,
  `FeeTo4` varchar(255) DEFAULT NULL,
  `FeeSplit5` varchar(255) DEFAULT NULL,
  `FeeTo5` varchar(255) DEFAULT NULL,
  `FeeSplit6` varchar(255) DEFAULT NULL,
  `FeeTo6` varchar(255) DEFAULT NULL,
  `Paul` int(11) DEFAULT NULL,
  `McBroom` int(11) DEFAULT NULL,
  `Pipeline` varchar(255) DEFAULT NULL,
  `MonthOfClose` varchar(255) DEFAULT NULL,
  `GrossThis` varchar(255) DEFAULT NULL,
  `GrossNext` varchar(255) DEFAULT NULL
) ENGINE=InnoDB  DEFAULT CHARSET=latin1 AUTO_INCREMENT=150 ;

--
-- Dumping data for table `company`
--

INSERT INTO `company` (`ID`, `Company`, `ELDate`, `IBCDate`, `EstCloseDate`, `ProjectName`, `ELExpirationDate`, `Status`, `DealType`, `DealSlot`, `ClosedDate`, `DeadDate`, `PrimaryBanker`, `PracticeArea`, `Industry`, `ProjectedTransactionSize`, `EnterpiseValue`, `FinalTransactionSize`, `ProjectedFee`, `FeeMinimum`, `EngagmentFee`, `FeeDetails`, `SplitToCorporate`, `MonthlyRetainer`, `FinalTotalSucessFee`, `OwnershipClass`, `ReferralType`, `ReferralSourceCompany`, `ReferralScourceInd`, `Description`, `TeamSplit1`, `Team1`, `TeamSplit2`, `Team2`, `TeamSplit3`, `Team3`, `TeamSplit4`, `Team4`, `TeamSplit5`, `Team5`, `TeamSplit6`, `Team6`, `FeeSplit1`, `FeeTo1`, `FeeSplit2`, `FeeTo2`, `FeeSplit3`, `FeeTo3`, `FeeSplit4`, `FeeTo4`, `FeeSplit5`, `FeeTo5`, `FeeSplit6`, `FeeTo6`, `Paul`, `McBroom`, `Pipeline`, `MonthOfClose`, `GrossThis`, `GrossNext`) VALUES
(24, 'ELDate', 'IBCDate', 'EstCloseDate', 'ProjectName', 'ELExpirationDate', 'Status', 'DealType', 'DealSlot', 'ClosedDate', 'DeadDate', NULL, 'PrimaryBanker', 'PracticeArea', 'Industry', 'ProjectedTransactionSize', 'EnterpiseValue', 'FinalTransaction Size', 'ProjectedFee', 'FeeMinimum', 'EngagmentFee', 'FeeDetails', 'SplitTo Corporate', 'MonthlyRetainer', 'FinalTotalSucessFee', 'OwnershipClass', 'ReferralType', 'ReferralSourceCompany', 'ReferralScourceInd', 'Description', 'TeamSplit1', 'Team1', 'TeamSplit2', 'Team2', 'TeamSplit3', 'Team3', 'TeamSplit4', 'Team4', 'TeamSplit5', 'Team5', 'TeamSplit6', 'Team6', 'FeeSplit1', 'FeeTo1', 'FeeSplit2', 'FeeTo2', 'FeeSplit3', 'FeeTo3', 'FeeSplit4', 'FeeTo4', 'FeeSplit5', 'FeeTo5', 'FeeSplit6', 'FeeTo6', 0, 0, 'Pipeline', 'MonthofClose', 'Gross This', 'GrossNext'),
(25, '', '', '11/29/2013', 'Project Valve', '', 'Closed', 'Advisory,M&A - Buy-side', 'Minimum', '1/6/2014', '', NULL, 'Len LaPorta', '', '', '$4,000,000', '< $10mm', '$4,000,000', '$90,000', '50000', '0', '', '', '0', '', '', 'Sole Sourced', '', 'Len Laporta', '', '', 'Len LaPorta', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 0, 0, 'Standard Margine Pipeline - Non-Corporate', '', '', ''),
(26, '1/6/2014', '', '7/30/2014', 'ADLT', '', 'Closed', 'Divestiture', 'Wheelhouse', '7/11/2014', '', NULL, 'Grant Garbers', '', 'Industrials - Aerospace/Defense', '$10,000,000', '$10mm - $25mm', '$16,500,000', '$500,000', '500000', '25000', '', '', '0', '825000', '', 'Practice to Practice', 'Sole Sourced', 'Tess Oxenstierna', '', '', 'Grant Garbers', '', 'Tess Oxenstierna', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 0, 0, 'Standard Margine Pipeline - Non-Corporate', '', '', ''),
(27, '5/29/2013', '', '', '', '', 'Dead', 'M&A - Sell-side,', 'Speculative', '', '5/27/2014', NULL, 'Dave Francione', '', '', '$15,000,000', '$10mm - $25mm', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 'Dave Francione', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 0, 0, 'Standard Margine Pipeline - Non-Corporate', '', '', ''),
(28, '10/8/2010', '', '10/31/2012', '', '', 'Dead', 'M&A - Sell-side', 'Speculative', '', '', NULL, 'Doug Usifer', '', '', '$30,000,000', '$25mm - $75mm', '', '$600,000', '0', '30000', '', '', '', '', '', '', '', 'Brad Hall', '', '', 'Doug Usifer', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 0, 0, 'Standard Margine Pipeline - Non-Corporate', '', '', ''),
(29, '3/4/2014', '3/3/2014', '', 'Project Alpha', '', 'Dead', 'Capital Formation - Debt,', 'Minimum', '', '', NULL, 'Bob Balaban', '', 'Business Services - Education and Training', '', '', '', '', '150000', '0', '', '', '25000', '', '', 'Corporate to Practice', '', 'Phil Seefried', '', '', 'Bob Balaban', '', 'Phil Seefried', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 0, 0, 'Standard Margine Pipeline - Non-Corporate', '', '', ''),
(30, '3/20/2014', '2/17/2014', '8/30/2014', 'Ambitions, Inc.', '', 'Under LOI', 'M&A - Sell-side', 'Wheelhouse', '', '', NULL, 'David Baker', 'Healthcare', 'Healthcare - Services - Home health care', '$40,000,000', '$25mm - $75mm', '', '$400,000', '', '0', '', '0.2', '', '', 'Privately Owned', 'IBS to Practice', 'BAML', '', '', '', 'David Baker', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 0, 1, 'IBS - Non-Corporate Pipeline', '11/30/2014', '400000', '0'),
(31, '4/16/2014', '4/14/2014', '', 'Ambre Energy North America, Inc.', '', 'In Market', 'Capital Formation - Debt', 'Speculative', '', '', NULL, 'Joel Schneyer', 'Energy & Natural Resources', 'Energy & Natural Resources - Mining - Coal & Uranium', '$169,000,000', '< $150mm', '', '$5,000,000', '', '40000', '', '0.2', '40000', '', 'Public', 'Sole Sourced', 'Sole Sourced', 'Ricardo Campoy', '1) Arranging acquisition capital to acquire Cloud Peak''s 50% joint venture interest in the Decker Coal Company; 2) Arranging acquisition capital to acquire Arch Coal Company''s 38% investment in the Millennium Bulk Terminal; 3) Assist in the divestiture of', '50%', 'Joel Schneyer', '50%', 'Ricardo Campoy', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 0, 0, 'Standard Margine Pipeline - Non-Corporate', '', '0', '0'),
(32, '', '4/7/2014', '', '', '', '', '', '', '', '', NULL, 'Melanie McFaddin', '', 'Business Services - Staffing & Recruitment', '', '', '', '', '', '', '', '', '', '', '', 'Sole Sourced', '', '', '', '', 'Melanie McFaddin', '999%', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 0, 0, 'Standard Margine Pipeline - Non-Corporate', '', '', ''),
(33, '', '5/12/2014', '', '', '', '', '', '', '', '', NULL, 'Darin Good', '', 'Industrials - Construction Svcs and Homebuilders', '', '', '', '', '', '', '', '', '', '', '', 'IBS to Practice', '', '', '', '', 'Darin Good', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 0, 0, 'Standard Margine Pipeline - Non-Corporate', '', '', ''),
(34, '', '4/14/2014', '', '', '', '', '', '', '', '', NULL, 'Melanie McFaddin', '', 'Business Services - Information Technology Services', '', '', '', '', '', '', '', '', '', '', '', 'Sole Sourced', '', '', '', '', 'Melanie McFaddin', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 0, 0, 'Standard Margine Pipeline - Non-Corporate', '', '', ''),
(35, '', '7/7/2014', '', '', '', '', '', '', '', '', NULL, 'David Baker', '', 'Healthcare - Devices', '', '', '', '', '', '', '', '', '', '', '', 'Sole Sourced', '', '', '', '', 'David Baker', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 0, 0, 'Standard Margine Pipeline - Non-Corporate', '', '', ''),
(36, '2/27/2014', '2/3/2014', '12/30/2014', 'Project Kickstart', '', 'Pre Market', 'M&A - Sell-side', 'Wheelhouse', '', '', NULL, 'Paul Janson', 'Industrials', 'Industrials - Other', '$25,000,000', '$25mm - $75mm', '', '$650,000', '450000', '0', '', '0.8', '12500', '', 'Privately Owned', 'Corporate to Practice', 'PKS', 'Paul Janson', '', '', 'Paul Janson', '', 'Bradford Reynolds', '', 'Brad Collins', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 1, 0, 'Corporate Revenue Pipeline', '8/5/2015', '0', '700000'),
(37, '3/26/2012', '', '12/31/2012', 'Project Hardware', '', 'In Market', 'M&A - Sell-side', 'Wheelhouse', '', '', NULL, 'Darin Good', 'Industrials', 'Industrials - Building Products & Construction Services', '$8,000,000', '< $10mm', '', '$400,000', '', '', '', '0.2', '', '', 'Privately Owned', 'Practice to Practice', 'Sole Sourced', 'Brian Mulvaney', 'Retainer Info : 10K per month for 3 months, then 5K per month for next 6 months.', '100%', 'Darin Good', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 0, 0, 'Standard Margine Pipeline - Non-Corporate', '12/31/2014', '400000', '0'),
(38, '6/3/2014', '5/12/2014', '', 'Project Horizon', '', 'In Market', 'M&A - Sell-side', 'Wheelhouse', '', '', NULL, 'Tyler Comann', 'Business Services', 'Technology/Media/Telecom - Other', '$15,000,000', '$10mm - $25mm', '', '$700,000', '', '', '', '0.2', '2500', '', 'Privately Owned', 'Sole Sourced', '', '', '', '100%', 'Tyler Comann', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 0, 0, 'Standard Margine Pipeline - Non-Corporate', '8/25/2015', '0', '700000'),
(39, '', '4/14/2014', '', '', '', '', '', '', '', '', NULL, 'Darin Good', '', 'Industrials - Building Products & Construction Services', '', '', '', '', '', '', '', '', '', '', '', 'SC to Practice', '', '', '', '', 'Darin Good', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 0, 0, 'Standard Margine Pipeline - Non-Corporate', '', '', ''),
(40, '', '8/4/2014', '', '', '', '', '', '', '', '', NULL, 'Len LaPorta', '', 'Industrials - Manufacturing, Equipment & Materials', '', '', '', '', '', '', '', '', '', '', '', 'SC to Practice', '', '', '', '', 'Len LaPorta', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 0, 0, 'Standard Margine Pipeline - Non-Corporate', '', '', ''),
(41, '9/5/2013', '', '', 'Bonneville Contracting & Technology', '', 'On Hold', 'M&A - Sell-side', 'Speculative', '', '', NULL, 'Tom McConnell', 'Business Services', 'Business Services - Physical & Cyber Security', '$11,000,000', '$10mm - $25mm', '', '$500,000', '', '', '', '0.2', '', '', 'Privately Owned', 'Sole Sourced', 'Sole Sourced', 'Thomas McConnell', '', '100%', 'Tom McConnell', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 0, 0, 'Standard Margine Pipeline - Non-Corporate', '', '0', '0'),
(42, '3/11/2014', '3/10/2014', '', 'BrandAds', '', 'Closed', 'M&A - Sell-side,', 'Wheelhouse', '5/6/2014', '', NULL, 'John Batdorf', '', 'Technology/Media/Telecom - Media - Internet Media and Marketing', '$20,000,000', '$10mm - $25mm', '$16,500,000', '$450,000', '450000', '0', '', '', '10000', '495000', '', 'Sole Sourced', '', 'John Batdorf', '', '', 'John Batdorf', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 0, 0, 'Standard Margine Pipeline - Non-Corporate', '', '', ''),
(43, '5/30/2013', '', '', '', '', 'Dead', 'Capital Formation - Debt', 'Minimum', '', '', NULL, 'William Harrison', '', '', '$7,000,000', '< $10mm', '', '$400,000', '400000', '0', '', '', '5000', '', '', '', '', '', '', '', 'William Harrison', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 0, 0, 'Standard Margine Pipeline - Non-Corporate', '', '', ''),
(44, '', '3/24/2014', '', '', '', '', '', '', '', '', NULL, 'Len LaPorta', '', 'Energy & Natural Resources - Forestry, Paper & Pulp', '', '', '', '', '', '', '', '', '', '', '', 'Sole Sourced', '', '', '', '', 'Len LaPorta', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 0, 0, 'Standard Margine Pipeline - Non-Corporate', '', '', ''),
(45, '12/6/2013', '', '10/30/2014', 'Project Gemstone', '', 'On Hold', 'Capital Formation - Debt', 'Wheelhouse', '', '', NULL, 'Paul Janson', 'Consumer Products', 'Real Estate - Other', '$30,000,000', '$25mm - $75mm', '', '$600,000', '', '', '', '0.5', '', '', 'Privately Owned', 'IBS to Practice', 'UBS', '', '', '', 'Paul Janson', '', 'Mike Swartz', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 1, 0, 'Corporate Revenue Pipeline', '', '0', '0'),
(46, '6/8/2012', '', '11/30/2012', 'Project Broadcast', '', 'On Hold', 'M&A - Sell-side', 'Wheelhouse', '', '', NULL, 'Bob Balaban', 'Business Services', 'Business Services - Education and Training', '$15,000,000', '$10mm - $25mm', '', '$525,000', '', '', '', '0.4', '', '', 'Privately Owned', 'IBS to Practice', 'Deutsche Bank Private Wealth Management', 'Sava Kobilarov', '', '100%', 'Bob Balaban', '', 'Chad Gardiner', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 1, 0, 'Corporate Revenue Pipeline', '1/1/2015', '0', '0'),
(47, '11/12/2013', '', '', 'Coronado Manufacturing, Inc.', '', 'On Hold', 'M&A - Sell-side', 'Wheelhouse', '', '', NULL, 'David Brinkley', 'Industrials', 'Industrials - Aerospace/Defense', '$13,000,000', '$10mm - $25mm', '', '$580,000', '', '', '', '0.3', '', '', 'Privately Owned', 'IBS to Practice', 'UBS', 'David Brinkley', '', '', 'David Brinkley', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 0, 1, 'IBS - Non-Corporate Pipeline', '3/10/2015', '0', '0'),
(48, '2/27/2014', '2/10/2014', '', 'Credit.com', '', 'Under LOI', 'M&A - Sell-side', 'Wheelhouse', '', '', NULL, 'Gary Moon', 'TMT', 'Technology/Media/Telecom - Other', '$40,000,000', '$25mm - $75mm', '', '$1,000,000', '750000', '25000', '', '0.15', '25000', '', 'Privately Owned', 'Sole Sourced', 'Sole Sourced', 'Gary Moon', '', '100%', 'Gary Moon', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 0, 0, 'Standard Margine Pipeline - Non-Corporate', '12/16/2014', '1200000', '0'),
(49, '4/9/2008', '', '', 'Carnaval', '', 'On Hold', 'M&A - Sell-side', 'Speculative', '', '', NULL, 'Horacio Facca', 'LATAM', 'Technology/Media/Telecom - Tech - Software', '$30,000,000', '$25mm - $75mm', '', '$1,000,000', '', '', '', '0.25', '', '', 'Privately Owned', 'Sole Sourced', 'Sole Sourced', 'Horacio Facca', 'Projections based on deals in CWI pipeline, which have had a 60% hit rate historically. Exchange rate as of 01/27/2011: 1R$ = 0.60US$. Accordingly, 2011e Revenues are approximately US$22mm. CWI has 500+ employees.', '', 'Horacio Facca', '100%', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 0, 0, 'Standard Margine Pipeline - Non-Corporate', '', '0', '0'),
(50, '7/30/2013', '', '1/31/2014', 'Digital Payment Technologies', '', 'Closed', 'M&A - Sell-side', 'Wheelhouse', '1/31/2014', '', NULL, 'Adrian Kingshott', '', '', '$25,000,000', '$25mm - $75mm', '$24,999,000', '$500,000', '400000', '0', '', '', '0', '625000', '', 'Sole Sourced', '', 'Adrian Kingshott', '', '', 'Adrian Kingshott', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 0, 0, 'Standard Margine Pipeline - Non-Corporate', '', '', ''),
(51, '4/23/2013', '', '', 'Project Slurry', '', 'In Market', 'Capital Formation - Debt', 'Speculative', '', '', NULL, 'Mike Swartz', 'Energy & Natural Resources', 'Energy & Natural Resources - Mining - Coal & Uranium', '$25,000,000', '$25mm - $75mm', '', '$500,000', '', '', '', '0.2', '', '', 'Privately Owned', 'IBS to Practice', 'BAML', 'Phillip Chang', 'No Financials.', '', 'Mike Swartz', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 0, 1, 'IBS - Non-Corporate Pipeline', '10/23/2014', '0', '0'),
(52, '1/6/2014', '', '9/30/2014', 'Project Diamond', '', 'Under LOI', 'M&A - Sell-side', 'Wheelhouse', '', '', NULL, 'Bob Balaban', 'Business Services', 'Business Services - Professional Services & Consulting', '$16,000,000', '$10mm - $25mm', '', '$750,000', '450000', '', '', '0.2', '10000', '', 'Privately Owned', 'IBS to Practice', 'Merrill Lynch & Co. Inc.', '', '', '', 'Bob Balaban', '', '', '', 'Chad Gardiner', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 0, 1, 'IBS - Non-Corporate Pipeline', '11/12/2014', '400000', '0'),
(53, '', '2/24/2014', '', '', '', '', '', '', '', '', NULL, 'Jerry Sturgill', '', 'Healthcare - Devices', '', '', '', '', '', '', '', '', '', '', '', 'Sole Sourced', '', '', '', '', 'Jerry Sturgill', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 0, 0, 'Standard Margine Pipeline - Non-Corporate', '', '', ''),
(54, '5/30/2013', '', '8/30/2014', 'Dynmark', '', 'On Hold', 'M&A - Sell-side', 'Wheelhouse', '', '', NULL, 'Gary Moon', 'TMT', 'Technology/Media/Telecom - Tech - Wireless', '$30,000,000', '$25mm - $75mm', '', '$900,000', '', '', '', '0.15', '', '', 'Privately Owned', 'Sole Sourced', 'Sole Sourced', 'Gary Moon', 'Similar to iLoop.', '100%', 'Gary Moon', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 0, 0, 'Standard Margine Pipeline - Non-Corporate', '', '0', '0'),
(55, '10/11/2012', '', '', '', '', 'Dead', 'M&A - Sell-side', 'Minimum', '', '', NULL, 'David Baker', '', '', '$5,000,000', '< $10mm', '', '', '', '15000', '', '', '0', '', '', '', '', 'David Baker', '', '', 'David Baker', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 0, 0, 'Standard Margine Pipeline - Non-Corporate', '', '', ''),
(56, '8/1/2013', '', '', '', '', 'Dead', 'M&A - Sell-side', 'Wheelhouse', '', '', NULL, 'Tess Oxenstierna', '', '', '$8,000,000', '< $10mm', '', '$400,000', '400000', '20000', '', '', '12000', '', '', '', '', 'Bob Balaban', '', '', 'Tess Oxenstierna', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 0, 0, 'Standard Margine Pipeline - Non-Corporate', '', '', ''),
(57, '4/29/2014', '4/28/2014', '', 'Eureka Petroleum', '', 'Pre Market', 'Capital Formation - Debt,Capital Formation - Equity', 'Wheelhouse', '', '', NULL, 'Macy/Pietravalle', 'Energy & Natural Resources', 'Energy & Natural Resources - Oil & Gas - E&P', '$100,000,000', '< $150mm', '', '$4,000,000', '750000', '0', '', '0.2', '20000', '', 'Privately Owned', 'IBS to Practice', 'BAML', '', '', '', 'Macy/Pietravalle', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 1, 0, 'Corporate Revenue Pipeline', '8/11/2015', '0', '4500000'),
(58, '11/2/2012', '', '', '', '', 'Dead', 'M&A - Sell-side,', 'Minimum', '', '', NULL, 'Bob Balaban', '', '', '$6,000,000', '< $10mm', '', '$300,000', '250000', '0', '', '', '5000', '', '', '', '', 'Bob Balaban', '', '', 'Bob Balaban', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 0, 0, 'Standard Margine Pipeline - Non-Corporate', '', '', ''),
(59, '2/3/2014', '5/5/2014', '9/30/2014', 'Project Sidecar', '', 'Under LOI', 'Capital Formation - Equity', 'Speculative', '', '', NULL, 'Adrian Kingshott', 'Financial Institutions', 'Financial Services - Insurance', '$10,000,000', '$10mm - $25mm', '', '$600,000', '', '50000', '', '0.3', '', '', 'Public', 'Sole Sourced', 'Sole Sourced', '', '', '100%', 'Adrian Kingshott', '', 'Bradford Reynolds', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 0, 0, 'Standard Margine Pipeline - Non-Corporate', '9/30/2014', '500000', '0'),
(60, '5/9/2013', '', '10/30/2014', 'Project FishTank', '', 'In Market', 'M&A - Sell-side', 'Wheelhouse', '', '', NULL, 'Peter Nam', 'Consumer Products', 'Consumer & Retail - Specialty Retailing', '$15,000,000', '$10mm - $25mm', '', '$500,000', '', '', '', '0.2', '', '', 'Privately Owned', 'Sole Sourced', 'Sole Sourced', 'Peter Nam', '', '100%', 'Peter Nam', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 0, 0, 'Standard Margine Pipeline - Non-Corporate', '12/30/2014', '450000', '0'),
(61, '6/1/2012', '', '', '', '', 'Dead', 'M&A - Sell-side', 'Wheelhouse', '', '', NULL, 'Tom McConnell', '', '', '$15,000,000', '$10mm - $25mm', '', '$620,000', '300000', '', '', '0', '10000', '', '', '', '', 'Phil Seefried', '', '', 'Tom McConnell', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 0, 0, 'Standard Margine Pipeline - Non-Corporate', '', '', ''),
(62, '1/1/2014', '', '3/30/2015', 'Project Blue', '', 'In Market', 'M&A - Sell-side', 'Wheelhouse', '', '', NULL, 'Tyler Comann', 'Consumer Products', 'Consumer & Retail - Organic/Natural Foods/Nutraceuticals (Healthy Living)', '$15,000,000', '$10mm - $25mm', '', '$400,000', '', '0', '', '0.2', '10000', '', 'Privately Owned', 'Sole Sourced', 'Sole Sourced', '', '', '100%', 'Tyler Comann', '', 'Bill Harrison', '', 'Shaun Kalnasy', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 0, 0, 'Standard Margine Pipeline - Non-Corporate', '10/28/2014', '0', '0'),
(63, '2/5/2014', '', '9/30/2014', 'Geosyntec Consultants, Inc.', '', 'Under LOI', 'Capital Formation - Equity,Divestiture', 'Minimum', '', '', NULL, 'Samrat Karnik', 'Industrials', 'Industrials - Technology - Controls, Instruments & Sensors', '$5,000,000', '< $10mm', '', '$300,000', '225000', '0', '', '0.2', '5000', '', 'Privately Owned', 'Sole Sourced', 'Sole Sourced', 'Samrat Karnik', '', '100%', 'Samrat Karnik', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 0, 0, 'Standard Margine Pipeline - Non-Corporate', '9/17/2014', '275000', '0'),
(64, '9/26/2011', '', '', 'Cherry', '', 'On Hold', 'M&A - Sell-side', 'Wheelhouse', '', '', NULL, 'Horacio Facca', 'LATAM', 'Technology/Media/Telecom - Telecom', '$79,000,000', '$75mm - $100mm', '', '$1,000,000', '', '', '', '0.2', '', '', 'Privately Owned', 'Sole Sourced', 'Sole Sourced', 'Horacio Facca', '', '', 'Horacio Facca', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 0, 0, 'Standard Margine Pipeline - Non-Corporate', '', '0', '0'),
(65, '', '7/7/2014', '', '', '', '', '', '', '', '', NULL, 'Ray McCormick', '', 'Energy & Natural Resources - Mining - Coal & Uranium', '', '', '', '', '', '', '', '', '', '', '', 'IBS to Practice', '', '', '', '', 'Ray McCormick', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 0, 0, 'Standard Margine Pipeline - Non-Corporate', '', '', ''),
(66, '6/2/2014', '5/30/2014', '', 'Project Pearl', '', 'Pre Market', 'M&A - Sell-side', 'Minimum', '', '', NULL, 'Bill Harrison', 'Consumer Products', 'Consumer & Retail - Branded Consumer/Private Label', '$8,000,000', '< $10mm', '', '$400,000', '250000', '25000', '', '0.2', '0', '', 'Private Equity Owned', 'Sole Sourced', '', '', '', '100%', 'Bill Harrison', '', 'Chad Gardiner', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 0, 0, 'Standard Margine Pipeline - Non-Corporate', '1/20/2015', '0', '400000'),
(67, '6/25/2013', '', '7/30/2014', 'Project Clare & Jacket', '', 'Closed', 'Divestiture', 'Minimum', '7/25/2014', '', NULL, 'Grant Garbers', '', '', '$15,000,000', '$10mm - $25mm', '$12,000,000', '$800,000', '300000', '0', '', '', '12000', '300000', '', 'Sole Sourced', 'Sole Sourced', 'Grant Garbers', '', '', 'Grant Garbers', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 0, 0, 'Standard Margine Pipeline - Non-Corporate', '', '', ''),
(68, '', '7/28/2014', '', '', '', '', '', '', '', '', NULL, 'Michael Swartz', '', 'Energy & Natural Resources - Oil & Gas - Refining & Storage', '', '', '', '', '', '', '', '', '', '', '', 'Sole Sourced', '', '', '', '', 'Michael Swartz', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 0, 0, 'Standard Margine Pipeline - Non-Corporate', '', '', ''),
(69, '12/11/2012', '', '9/14/2013', '', '', 'Dead', 'M&A - Sell-side', 'Wheelhouse', '', '', NULL, 'Len LaPorta', '', '', '$100,000,000', '< $150mm', '', '$2,500,000', '1000000', '10000', '', '9.99', '8000', '', '', '', 'Aegean Baltic Bank S.A.', '', '', '', 'Len LaPorta', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 0, 0, 'Standard Margine Pipeline - Non-Corporate', '', '', ''),
(70, '6/10/2013', '', '', '', '', 'Dead', 'Capital Formation - Equity', 'Speculative', '', '5/28/2014', NULL, 'Tess Oxenstierna', '', '', '$10,000,000', '$10mm - $25mm', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 'Tess Oxenstierna', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 0, 0, 'Standard Margine Pipeline - Non-Corporate', '', '', ''),
(71, '7/17/2014', '', '', 'Project Cooler', '', 'In Market', 'M&A - Buy-side', 'Speculative', '', '', NULL, 'Bill Harrison', 'Consumer Products', 'Consumer & Retail - Specialty Retailing', '$20,000,000', '$10mm - $25mm', '', '', '', '0', '', '0.2', '10000', '', 'Private Equity Owned', 'Sole Sourced', 'Igloo Products', '', '', '100%', 'Bill Harrison', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 0, 0, 'Standard Margine Pipeline - Non-Corporate', '', '0', '0'),
(72, '6/26/2012', '', '', '', '6/25/2013', 'Dead', 'M&A - Sell-side', 'Minimum', '', '', NULL, 'Tess Oxenstierna', '', '', '$15,000,000', '$10mm - $25mm', '', '$450,000', '300000', '', '', '', '3500', '', '', '', '', '', '', '', 'Tess Oxenstierna', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 0, 0, 'Standard Margine Pipeline - Non-Corporate', '', '', ''),
(73, '1/7/2014', '', '9/30/2014', 'Project Innovation', '', 'Under LOI', 'M&A - Sell-side', 'Wheelhouse', '', '', NULL, 'Gary Moon', 'TMT', 'Technology/Media/Telecom - Telecom - Services', '$13,000,000', '$10mm - $25mm', '', '$600,000', '500000', '0', '', '0.15', '10000', '', 'Privately Owned', 'Sole Sourced', 'Sole Sourced', 'Gary Moon', '', '100%', 'Gary Moon', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 0, 0, 'Standard Margine Pipeline - Non-Corporate', '9/16/2014', '500000', '0'),
(74, '', '7/21/2014', '', '', '', '', '', '', '', '', NULL, 'Michael Swartz', '', 'Energy & Natural Resources - Alternative - Solar', '', '', '', '', '', '', '', '', '', '', '', 'IBS to Practice', '', '', '', '', 'Michael Swartz', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 0, 0, 'Standard Margine Pipeline - Non-Corporate', '', '', ''),
(75, '5/3/2013', '', '', '', '', 'Dead', 'Capital Formation - Equity', 'Wheelhouse', '', '5/27/2014', NULL, 'Gary Moon', '', '', '$45,000,000', '$25mm - $75mm', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 'Gary Moon', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 0, 0, 'Standard Margine Pipeline - Non-Corporate', '', '', ''),
(76, '1/23/2014', '1/13/2014', '10/1/2014', 'Project Focus', '', 'In Market', 'Capital Formation - Debt', 'Minimum', '', '', NULL, 'Darin Good', 'Consumer Products', 'Consumer & Retail - Specialty Retailing', '$12,500,000', '$10mm - $25mm', '', '$400,000', '200000', '', '', '0.2', '', '', 'Privately Owned', 'Sole Sourced', 'Sole Sourced', 'Darin Good', '', '100%', 'Darin Good', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 0, 0, 'Standard Margine Pipeline - Non-Corporate', '9/29/2014', '200000', '0'),
(77, '9/10/2013', '', '', 'Isonas', '', 'Closed', 'Capital Formation - Equity', 'Speculative', '9/17/2014', '', NULL, 'Tom McConnell', 'Business Services', 'Business Services - Physical & Cyber Security', '$15,000,000', '$10mm - $25mm', '$3,000,000', '$600,000', '450000', '', '', '0.2', '7500', '207500', 'Privately Owned', 'Sole Sourced', 'Sole Sourced', 'Thomas McConnell', '', '100%', 'Tom McConnell', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 0, 0, 'Standard Margine Pipeline - Non-Corporate', '9/30/2014', '0', '0'),
(78, '1/29/2014', '', '', 'Project Apex', '', 'Dead', 'M&A - Sell-side, Licensing', 'Wheelhouse', '', '', NULL, 'Joel Schneyer', '', 'Energy & Natural Resources - Oil & Gas - E&P', '$50,000,000', '$25mm - $75mm', '', '$750,000', '0', '0', '', '', '0', '', '', 'IBS to Practice', 'Deutsche Bank Private Wealth Management', 'Jay Pickett', '', '', 'Joel Schneyer', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 0, 0, 'Standard Margine Pipeline - Non-Corporate', '', '', ''),
(79, '4/18/2014', '4/28/2014', '', 'Joshi Technologies International', '', 'In Market', 'Capital Formation - Debt,Capital Formation - Equity', 'Wheelhouse', '', '', NULL, 'Macy/Pietravalle', 'Energy & Natural Resources', 'Energy & Natural Resources - Energy Services - Drilling & Energy Fluids', '$50,000,000', '$25mm - $75mm', '', '$2,000,000', '', '0', '', '0.4', '10000', '', 'Privately Owned', 'IBS to Practice', 'BAML', '', '', '', 'Paul Janson', '', 'Bradford Reynolds', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 1, 0, 'Corporate Revenue Pipeline', '12/10/2014', '3000000', '0'),
(80, '5/5/2014', '', '', 'Project Citation', '', 'In Market', 'M&A - Sell-side', 'Wheelhouse', '', '', NULL, 'Samrat Karnik', 'Industrials', 'Industrials - Manufacturing, Equipment & Materials', '$20,000,000', '$10mm - $25mm', '', '$500,000', '650000', '', '', '0.38', '', '', 'Private Equity Owned', 'MA to Practice', 'Catalyst Corporate Finance LLP', '', '', '', 'Samrat Karnik', '', 'Paul Janson', '', 'Bradford Reynolds', '', 'Brad Collins', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 1, 0, 'Corporate Revenue Pipeline', '10/18/2014', '650000', '0'),
(81, '9/2/2013', '', '6/5/2014', 'Project Midway', '', 'Closed', 'Capital Formation - Debt,Recapitalization,', 'Wheelhouse', '7/3/2014', '', NULL, 'Len LaPorta', '', '', '$62,000,000', '$25mm - $75mm', '$62,000,000', '$2,200,000', '650000', '25000', '', '', '25000', '1989025', '', 'SC to Practice', 'Headwaters SC', 'Jim Bly', '', '', 'Len LaPorta', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 0, 0, 'Standard Margine Pipeline - Non-Corporate', '', '', ''),
(82, '7/17/2014', '', '', 'Project Benefit', '', 'Pre Market', 'Capital Formation - Debt', 'Wheelhouse', '', '', NULL, 'Phil Seefried', 'Business Services', 'Business Services - Support Services - BPO', '$25,000,000', '$25mm - $75mm', '', '$750,000', '450000', '', '', '0.8', '', '', 'Privately Owned', 'SC to Practice', '', '', '', '', 'Phil Seefried', '', 'Bradford Reynolds', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 1, 0, 'Corporate Revenue Pipeline', '12/23/2014', '800000', '0'),
(83, '10/2/2013', '', '', '', '', 'Dead', 'M&A - Sell-side', 'Wheelhouse', '', '5/27/2014', NULL, 'Gary Moon', '', '', '$45,000,000', '$25mm - $75mm', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 'Gary Moon', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 0, 0, 'Standard Margine Pipeline - Non-Corporate', '', '', ''),
(84, '10/15/2013', '', '', 'Project Armour', '', 'In Market', 'M&A - Sell-side', 'Wheelhouse', '', '', NULL, 'Jack Maier', 'Industrials', 'Industrials - Manufacturing, Equipment & Materials', '$77,000,000', '$75mm - $100mm', '', '$1,900,000', '', '', '', '0.85', '', '', 'Privately Owned', 'IBS to Practice', 'UBS', '', '', '', 'Jack Maier', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 1, 0, 'Corporate Revenue Pipeline', '1/30/2015', '0', '1600000'),
(85, '7/31/2011', '', '', '', '', 'Dead', 'M&A - Sell-side,', 'Wheelhouse', '', '4/4/2014', NULL, 'Doug Usifer', '', '', '$21,000,000', '$10mm - $25mm', '', '$675,000', '0', '', '', '', '5000', '', '', '', '', 'Brad Hall', '', '', 'Doug Usifer', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 0, 0, 'Standard Margine Pipeline - Non-Corporate', '', '', ''),
(86, '10/17/2013', '', '', '', '', 'Dead', 'M&A - Sell-side', 'Wheelhouse', '', '', NULL, 'David Baker', '', '', '$50,000,000', '$25mm - $75mm', '', '$2,000,000', '400000', '0', '', '', '10000', '', '', '', '', 'Gary Moon', '', '', 'David Baker', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 0, 0, 'Standard Margine Pipeline - Non-Corporate', '', '', ''),
(87, '10/17/2012', '', '', 'Mercer Group International', '', 'In Market', 'M&A - Sell-side', 'Wheelhouse', '', '', NULL, 'Doug Usifer', 'Industrials', 'Business Services - Waste Management & Recycling', '$25,000,000', '$10mm - $25mm', '', '$475,000', '', '', '', '0.2', '', '', 'Privately Owned', 'Sole Sourced', 'Sole Sourced', 'Doug Usifer', 'Privately Owned.', '100%', 'Doug Usifer', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 0, 0, 'Standard Margine Pipeline - Non-Corporate', '', '0', '0'),
(88, '3/20/2014', '3/24/2014', '', 'Project AIM', '', 'In Market', 'M&A - Sell-side', 'Wheelhouse', '', '', NULL, 'Tyler Comann', 'Business Services', 'Business Services - Information Technology Services', '$30,000,000', '$25mm - $75mm', '', '$750,000', '500000', '', '', '0.4', '10000', '', 'Privately Owned', 'Sole Sourced', 'Sole Sourced', '', '', '100%', 'Tyler Comann', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 0, 0, 'Standard Margine Pipeline - Non-Corporate', '11/30/2014', '850000', '0'),
(89, '9/10/2013', '', '', 'Mirasys', '', 'Under LOI', 'M&A - Sell-side', 'Minimum', '', '', NULL, 'Tom McConnell', 'Business Services', 'Business Services - Physical & Cyber Security', '$25,000,000', '$10mm - $25mm', '', '$1,000,000', '', '', '', '0.2', '', '', 'Privately Owned', 'Sole Sourced', 'Sole Sourced', 'Thomas McConnell', '', '100%', 'Tom McConnell', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 0, 0, 'Standard Margine Pipeline - Non-Corporate', '10/28/2014', '0', '0'),
(90, '1/27/2014', '', '', 'MKS Instruments, Inc.', '', 'Dead', 'M&A - Buy-side,', 'Speculative', '', '5/5/2014', NULL, 'Grant Garbers', '', 'Industrials - Technology - Controls, Instruments & Sensors', '$17,000,000', '$10mm - $25mm', '', '$300,000', '300000', '0', '', '', '15000', '', '', 'Sole Sourced', '', 'John Ippolito', '', '', 'Grant Garbers', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 0, 0, 'Standard Margine Pipeline - Non-Corporate', '', '', ''),
(91, '8/2/2013', '', '', 'Project Pipe', '', 'In Market', 'M&A - Sell-side', 'Speculative', '', '', NULL, 'Darin Good', 'Industrials', 'Industrials - Building Products & Construction Services', '$15,000,000', '$10mm - $25mm', '', '$750,000', '', '', '', '0.2', '', '', 'Privately Owned', 'Sole Sourced', 'Sole Sourced', 'Brian Krehbiel', '', '100%', 'Darin Good', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 0, 0, 'Standard Margine Pipeline - Non-Corporate', '1/19/2015', '0', '1000000'),
(92, '6/18/2013', '', '', 'NexLube', '', 'In Market', 'Capital Formation - Equity', 'Wheelhouse', '', '', NULL, 'CJ Hummel', 'Energy & Natural Resources', 'Energy & Natural Resources - Oil & Gas - Refining & Storage', '$40,000,000', '$25mm - $75mm', '', '$600,000', '', '', '', '0.2', '', '', 'Privately Owned', 'Sole Sourced', 'Sole Sourced', 'CJ Hummel', '', '100%', 'CJ Hummel', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 0, 0, 'Standard Margine Pipeline - Non-Corporate', '', '0', '0'),
(93, '', '2/17/2014', '', '', '', '', '', '', '', '', NULL, 'David Baker', '', 'Healthcare - Services - Home health care', '', '', '', '', '', '', '', '', '', '', '', 'Sole Sourced', '', '', '', '', 'David Baker', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 0, 0, 'Standard Margine Pipeline - Non-Corporate', '', '', ''),
(94, '4/1/2013', '', '', 'Onsite Health', '', 'On Hold', 'M&A - Sell-side', 'Minimum', '', '', NULL, 'Phil Seefried', 'Healthcare', 'Healthcare - Services', '$30,000,000', '$25mm - $75mm', '', '$325,000', '', '', '', '0.6', '', '', 'Private Equity Owned', 'Sole Sourced', 'Sole Sourced', 'Phil Seefried', 'No Financials.', '', 'Phil Seefried', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 1, 0, 'Corporate Revenue Pipeline', '1/30/2015', '0', '400000'),
(95, '', '', '9/12/2012', '', '1/31/2013', 'Dead', 'Capital Formation - Debt', 'Speculative', '', '3/25/2014', NULL, 'Ricardo Campoy', '', '', '$72,000,000', '$25mm - $75mm', '', '$1,800,000', '0', '0', '', '', '0', '', '', '', '', 'Joel Schneyer', '', '', 'Ricardo Campoy', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 0, 0, 'Standard Margine Pipeline - Non-Corporate', '', '', ''),
(96, '', '3/10/2014', '', '', '', '', '', '', '', '', NULL, 'Chad Gardiner', '', 'Business Services - Professional Services & Consulting', '', '', '', '', '', '', '', '', '', '', '', 'IBS to Practice', '', '', '', '', 'Chad Gardiner', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 0, 0, 'Standard Margine Pipeline - Non-Corporate', '', '', ''),
(97, '7/21/2014', '7/16/2014', '', 'Project Black Bear', '', 'Pre Market', 'Capital Formation - Equity', 'Wheelhouse', '', '', NULL, 'Macy/Pietravalle', 'Energy & Natural Resources', 'Energy & Natural Resources - Oil & Gas - E&P', '$50,000,000', '$25mm - $75mm', '', '$1,500,000', '450000', '20000', '', '0.4', '10000', '', 'Privately Owned', 'IBS to Practice', 'Barclays', '', '', '', 'Macy/Pietravalle', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 1, 0, 'Corporate Revenue Pipeline', '6/2/2015', '0', '2000000'),
(98, '4/10/2013', '', '', '', '', 'Dead', 'Capital Formation - Equity', 'Speculative', '', '4/4/2014', NULL, 'Jeff Ackerman', '', '', '$50,000,000', '$25mm - $75mm', '', '$2,000,000', '750000', '0', '', '', '15000', '', '', '', '', 'Jeff Ackerman', '', '', 'Jeff Ackerman', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 0, 0, 'Standard Margine Pipeline - Non-Corporate', '', '', ''),
(99, '10/8/2013', '', '7/30/2014', 'Perfect Market', '', 'Closed', 'M&A - Sell-side', 'Wheelhouse', '7/29/2014', '', NULL, 'Sun Jen Yung', '', '', '$35,000,000', '$25mm - $75mm', '$34,000,000', '$1,000,000', '800000', '0', '', '', '12500', '1023250', '', 'Sole Sourced', 'Sole Sourced', 'Sun Jen Yung', '', '', 'Sun Jen Yung', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 0, 0, 'Standard Margine Pipeline - Non-Corporate', '', '', ''),
(100, '5/2/2014', '4/3/2014', '', 'Project Bond', '', 'Pre Market', 'M&A - Sell-side', 'Wheelhouse', '', '', NULL, 'Ian Cookson', 'Industrials', 'Industrials - Aerospace/Defense', '$20,000,000', '$10mm - $25mm', '', '$900,000', '550000', '', '', '0.3', '15000', '', 'Privately Owned', 'Sole Sourced', 'Sole Sourced', 'Ian Cookson', '', '100%', 'Ian Cookson', '', 'Olivia Moran', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 0, 0, 'Standard Margine Pipeline - Non-Corporate', '3/31/2015', '0', '550000'),
(101, '6/23/2014', '6/9/2014', '', 'Project Distributed Generation', '', 'Pre Market', 'Capital Formation - Equity', 'Wheelhouse', '', '', NULL, 'Mike Swartz', 'Energy & Natural Resources', 'Energy & Natural Resources - Alternative - Solar', '$30,000,000', '$25mm - $75mm', '', '$750,000', '350000', '0', '', '0.2', '0', '', 'Privately Owned', 'Sole Sourced', '', '', '', '50%', 'Mike Swartz', '50%', 'CJ Hummel', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 0, 0, 'Standard Margine Pipeline - Non-Corporate', '8/19/2015', '0', '0'),
(102, '', '', '', '', '', 'Dead', 'M&A - Sell-side', 'Wheelhouse', '', '5/27/2014', NULL, 'Bob Balaban', '', '', '$25,000,000', '$25mm - $75mm', '', '', '', '', '', '0.35', '', '', '', '', '', '', '', '', 'Paul Janson', '', 'Chad Gardiner', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 1, 0, 'Corporate Revenue Pipeline', '2/1/2015', '0', '0'),
(103, '3/11/2013', '', '', '', '', 'Dead', 'Licensing', 'Minimum', '', '8/6/2014', NULL, '', '', '', '$5,000,000', '$10mm - $25mm', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 0, 0, 'Standard Margine Pipeline - Non-Corporate', '', '', ''),
(104, '5/8/2013', '', '', 'Project Crowd', '', 'On Hold', 'M&A - Sell-side', 'Minimum', '', '', NULL, 'Bob Balaban', 'Business Services', 'Business Services - Support Services - BPO', '$7,000,000', '< $10mm', '', '$300,000', '', '', '', '0.2', '', '', 'Privately Owned', 'Sole Sourced', 'Sole Sourced', 'Bob Balaban', '', '100%', 'Bob Balaban', '', 'Chad Gardiner', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 0, 0, 'Standard Margine Pipeline - Non-Corporate', '', '0', '0'),
(105, '', '', '', '', '', 'Dead', 'Advisory', 'Minimum', '', '5/28/2014', NULL, 'Tess Oxenstierna', '', '', '$400,000', '< $10mm', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 'Tess Oxenstierna', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 0, 0, 'Standard Margine Pipeline - Non-Corporate', '', '', ''),
(106, '3/20/2012', '', '7/30/2014', 'Project Talk 3', '', 'In Market', 'M&A - Buy-side', 'Minimum', '', '', NULL, 'Bob Balaban', 'Business Services', 'Business Services - Support Services - Call Centers', '$8,000,000', '$10mm - $25mm', '', '$500,000', '', '', '', '0.3', '', '', 'Privately Owned', 'IBS to Practice', 'UBS', '', '', '', 'Bob Balaban', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 0, 0, 'IBS - Non-Corporate Pipeline', '', '0', '0'),
(107, '', '', '', 'Project Talk', '', 'Closed', 'M&A - Buy-side', 'Speculative', '5/5/2014', '', NULL, 'Bob Balaban', '', '', '$9,000,000', '$10mm - $25mm', '$25,000,000', '$750,000', '750000', '', '', '', '', '1375000', '', 'IBS to Practice', 'UBS', '', '', '', 'Bob Balaban', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 0, 0, 'Standard Margine Pipeline - Non-Corporate', '', '', ''),
(108, '7/10/2012', '', '', '', '', 'Dead', 'Capital Formation - Equity', 'Minimum', '', '4/4/2014', NULL, 'Tom McConnell', '', '', '$7,500,000', '< $10mm', '', '$300,000', '0', '', '', '', '10000', '', '', '', '', 'Len Laporta', '', '', 'Tom McConnell', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 0, 0, 'Standard Margine Pipeline - Non-Corporate', '', '', ''),
(109, '4/23/2014', '4/7/2014', '', 'RAVN Alaska', '', 'Pre Market', 'M&A - Sell-side', 'Wheelhouse', '', '', NULL, 'Jack Maier', 'Industrials', 'Industrials - Aerospace/Defense', '$150,000,000', '< $150mm', '', '$3,000,000', '1000000', '20000', '', '0.5', '20000', '', 'Privately Owned', 'IBS to Practice', 'Barclays', '', '', '', 'Jack Maier', '', 'Ian Cookson', '', 'Brad Collins', '', 'Olivia Moran', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 1, 0, 'Standard Margine Pipeline - Non-Corporate', '2/18/2015', '0', '2500000'),
(110, '6/5/2013', '', '', 'Relevant Ads', '', 'In Market', 'Capital Formation - Equity,M&A - Sell-side', 'Minimum', '', '', NULL, 'John Batdorf', 'TMT', 'Technology/Media/Telecom - Tech - Software', '$25,000,000', '$25mm - $75mm', '', '$1,000,000', '', '', '', '0.15', '', '', 'Privately Owned', 'Sole Sourced', 'Sole Sourced', 'John Batdorf', '', '', 'John Batdorf', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 0, 0, 'Standard Margine Pipeline - Non-Corporate', '11/19/2014', '0', '0'),
(111, '10/25/2013', '', '', 'Restaurant.com, Inc.', '', 'In Market', 'M&A - Sell-side,', 'Wheelhouse', '', '', NULL, 'Sun Jen Yung', 'TMT', 'Technology/Media/Telecom - Media - Internet Media and Marketing', '$40,000,000', '$25mm - $75mm', '', '$1,250,000', '', '', '', '', '', '', 'Privately Owned', 'Practice to Practice', 'Sole Sourced', 'David Francione', '', '', 'Sun Jen Yung', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 0, 0, 'Standard Margine Pipeline - Non-Corporate', '', '', ''),
(112, '2/13/2014', '1/20/2014', '', 'Project Protect', '', 'On Hold', 'M&A - Sell-side', 'Speculative', '', '', NULL, 'Jerry Sturgill', 'Consumer Products', 'Consumer & Retail - Other', '$17,500,000', '$10mm - $25mm', '', '$525,000', '420000', '0', '', '0.2', '10000', '', 'Privately Owned', 'Sole Sourced', 'Sole Sourced', 'Jerry Sturgill', '', '100%', 'Jerry Sturgill', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 0, 0, 'Standard Margine Pipeline - Non-Corporate', '', '0', '0'),
(113, '4/5/2013', '', '', 'Project X', '', 'Closed', 'Capital Formation - Equity', 'Minimum', '9/29/2014', '', NULL, 'Tom McConnell', 'Business Services', 'Technology/Media/Telecom - Tech - Software', '$10,000,000', '$10mm - $25mm', '', '$430,000', '430000', '0', '', '0.2', '5000', '560000', 'Privately Owned', 'Sole Sourced', '', 'Thomas McConnell', '', '100%', 'Tom McConnell', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 0, 0, 'Standard Margine Pipeline - Non-Corporate', '8/31/2014', '430000', '0'),
(114, '', '4/14/2014', '', '', '', '', '', '', '', '', NULL, 'Horacio Facca', '', 'Energy & Natural Resources - Mining', '', '', '', '', '', '', '', '', '', '', '', 'Sole Sourced', '', '', '', '', 'Horacio Facca', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 0, 0, 'Standard Margine Pipeline - Non-Corporate', '', '', ''),
(115, '12/20/2012', '', '', '', '', 'Dead', 'M&A - Sell-side', 'Minimum', '', '7/31/2014', NULL, '', '', '', '$17,000,000', '$10mm - $25mm', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 0, 0, 'Standard Margine Pipeline - Non-Corporate', '', '', ''),
(116, '3/7/2014', '1/20/2014', '', 'Project Quorum', '', 'In Market', 'M&A - Buy-side', 'Speculative', '', '', NULL, 'Ted Kinsman', 'Energy & Natural Resources', 'Energy & Natural Resources - Energy Services', '$19,915,000', '$10mm - $25mm', '', '$995,750', '500000', '', '', '0.2', '0', '', 'Privately Owned', 'Sole Sourced', 'Sole Sourced', 'Sam Hill', 'Quorum has submitted an initial LOI to acquire SK for $19.9mm.', '50%', 'Ted Kinsman', '50%', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 0, 0, 'Standard Margine Pipeline - Non-Corporate', '', '0', '0'),
(117, '6/11/2013', '', '', '', '', 'Dead', 'Capital Formation - Equity', 'Wheelhouse', '', '', NULL, 'Jeff Ackerman', '', '', '$8,500,000', '< $10mm', '', '$400,000', '300000', '', '', '', '10000', '', '', '', '', '', '', '', 'Jeff Ackerman', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 0, 0, 'Standard Margine Pipeline - Non-Corporate', '', '', ''),
(118, '', '3/24/2014', '', '', '', '', '', '', '', '', NULL, 'Sun Jen Yung', '', 'Technology/Media/Telecom - Tech', '', '', '', '', '', '', '', '', '', '', '', 'Sole Sourced', '', '', '', '', 'Sun Jen Yung', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 0, 0, 'Standard Margine Pipeline - Non-Corporate', '', '', ''),
(119, '11/1/2012', '', '', 'Project Yellowstone', '', 'In Market', 'M&A - Sell-side', 'Minimum', '', '', NULL, 'Bob Balaban', 'Business Services', 'Business Services - Engineering, Architecture, Design Firms', '$7,000,000', '< $10mm', '', '$360,000', '', '', '', '0.2', '', '', 'Privately Owned', 'Sole Sourced', 'Sole Sourced', 'Bob Balaban', '', '100%', 'Bob Balaban', '', 'Chad Gardiner', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 0, 0, 'Standard Margine Pipeline - Non-Corporate', '', '0', '0'),
(120, '6/17/2013', '', '', '', '', 'Dead', 'Capital Formation - Debt, Capital Formation - Equity', 'Minimum', '', '5/27/2014', NULL, 'Michael Swartz', '', '', '$10,000,000', '$10mm - $25mm', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 'Michael Swartz', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 0, 0, 'Standard Margine Pipeline - Non-Corporate', '', '', ''),
(121, '5/27/2014', '', '', 'Project Gusto', '', 'Pre Market', 'M&A - Sell-side', 'Wheelhouse', '', '', NULL, 'Doug Usifer', 'Chemicals & Plastics', 'Industrials - Chemicals', '$90,000,000', '$75mm - $100mm', '', '$1,800,000', '500000', '50000', '', '0.36', '0', '', 'Privately Owned', 'IBS to Practice', 'BAML', '', '', '', 'Doug Usifer', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 1, 0, 'Corporate Revenue Pipeline', '3/8/2015', '0', '1000000'),
(122, '2/13/2014', '3/3/2014', '8/30/2014', 'Project Dairy', '', 'Closed', 'M&A - Sell-side', 'Minimum', '8/22/2014', '', NULL, 'Dale Heims', 'Consumer Products', 'Consumer & Retail - Agribusiness', '$14,000,000', '$10mm - $25mm', '$10,000,000', '$400,000', '250000', '25000', '', '0.2', '0', '250000', 'Privately Owned', 'IBS to Practice', 'UBS', '', '', '', 'Dale Heims', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 0, 1, 'IBS - Non-Corporate Pipeline', '8/31/2014', '250000', '0'),
(123, '4/29/2013', '', '', 'Tecopesca', '', 'In Market', 'M&A - Sell-side', 'Speculative', '', '', NULL, 'Horacio Facca', 'LATAM', 'Consumer & Retail - Food Processing and Distribution', '$120,000,000', '< $150mm', '', '$6,300,000', '', '', '', '0.2', '', '', 'Privately Owned', 'IBS to Practice', 'BAML', 'Lily Tapia', 'Financials include Tecopesca, Bilbosa, T+B and Manabita. All companies are being sold as a group.', '', 'Horacio Facca', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 0, 1, 'IBS - Non-Corporate Pipeline', '12/31/2014', '0', '0'),
(124, '9/4/2013', '', '', 'Project Dos Rios', '', 'Pre Market', 'M&A - Sell-side', 'Speculative', '', '', NULL, 'Peter Nam', 'Energy & Natural Resources', 'Energy & Natural Resources - Oil & Gas - Refining & Storage', '$72,500,000', '$25mm - $75mm', '', '$1,500,000', '', '', '', '0.2', '', '', 'Privately Owned', 'Sole Sourced', 'Sole Sourced', 'Peter Nam', '', '100%', 'Peter Nam', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 0, 0, 'Standard Margine Pipeline - Non-Corporate', '', '0', '0');
INSERT INTO `company` (`ID`, `Company`, `ELDate`, `IBCDate`, `EstCloseDate`, `ProjectName`, `ELExpirationDate`, `Status`, `DealType`, `DealSlot`, `ClosedDate`, `DeadDate`, `PrimaryBanker`, `PracticeArea`, `Industry`, `ProjectedTransactionSize`, `EnterpiseValue`, `FinalTransactionSize`, `ProjectedFee`, `FeeMinimum`, `EngagmentFee`, `FeeDetails`, `SplitToCorporate`, `MonthlyRetainer`, `FinalTotalSucessFee`, `OwnershipClass`, `ReferralType`, `ReferralSourceCompany`, `ReferralScourceInd`, `Description`, `TeamSplit1`, `Team1`, `TeamSplit2`, `Team2`, `TeamSplit3`, `Team3`, `TeamSplit4`, `Team4`, `TeamSplit5`, `Team5`, `TeamSplit6`, `Team6`, `FeeSplit1`, `FeeTo1`, `FeeSplit2`, `FeeTo2`, `FeeSplit3`, `FeeTo3`, `FeeSplit4`, `FeeTo4`, `FeeSplit5`, `FeeTo5`, `FeeSplit6`, `FeeTo6`, `Paul`, `McBroom`, `Pipeline`, `MonthOfClose`, `GrossThis`, `GrossNext`) VALUES
(125, '6/9/2014', '6/2/2014', '', 'Project Eagle', '', 'Pre Market', 'Capital Formation - Equity', 'Minimum', '', '', NULL, 'Rick deNey', 'Industrials', 'Industrials - Aerospace/Defense', '$8,000,000', '< $10mm', '', '$480,000', '300000', '0', '', '0.2', '10000', '', 'Privately Owned', 'Sole Sourced', 'WestComm, Inc.', '', '', '100%', 'Rick deNey', '', 'Len LaPorta', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 0, 0, 'Standard Margine Pipeline - Non-Corporate', '', '0', '0'),
(126, '11/12/2013', '', '8/30/2014', 'Project Passport', '', 'Closed', 'M&A - Sell-side,', 'Wheelhouse', '7/31/2014', '', NULL, 'Dave Francione', '', '', '$40,000,000', '$25mm - $75mm', '$53,600,000', '$750,000', '750000', '20000', '', '9.99', '20000', '1340000', '', 'IBS to Practice', 'BAML', '', '', '', 'Dave Francione', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 0, 0, 'Standard Margine Pipeline - Non-Corporate', '', '', ''),
(127, '3/19/2014', '', '', 'White Mountain', '', 'In Market', 'M&A - Sell-side', 'Minimum', '', '', NULL, 'Jeff Ackerman', 'Consumer Products', 'Consumer & Retail - Apparel', '$50,000,000', '$25mm - $75mm', '', '$162,500', '162500', '0', '', '0.2', '0', '', 'Privately Owned', 'Sole Sourced', 'Sole Sourced', 'Jeff Ackerman', '', '100%', 'Jeff Ackerman', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 0, 0, 'Standard Margine Pipeline - Non-Corporate', '11/30/2014', '180000', '0'),
(128, '', '6/6/2014', '', '', '', '', '', '', '', '', NULL, 'William Harrison', '', 'Consumer & Retail - Apparel', '', '', '', '', '', '', '', '', '', '', '', 'IBS to Practice', '', '', '', '', 'William Harrison', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 0, 0, 'Standard Margine Pipeline - Non-Corporate', '', '', ''),
(129, '11/4/2013', '', '4/1/2014', 'Project Wagon', '', 'Closed', 'M&A - Sell-side,', 'Wheelhouse', '7/3/2014', '', NULL, 'Phil Seefried', '', '', '$40,000,000', '$25mm - $75mm', '$50,000,000', '$800,000', '400000', '50000', '', '', '0', '1084480', '', 'Corporate to Practice', 'Housatonic Partners', 'Phil Seefried', '', '', 'Phil Seefried', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 0, 0, 'Standard Margine Pipeline - Non-Corporate', '', '', ''),
(130, '', '', '', 'Weiss', '', 'Closed', 'M&A - Sell-side', 'Minimum', '7/31/2014', '', NULL, 'Dave Francione', '', '', '', '', '$1,500,000', '', '', '', '', '', '', '', '', 'Sole Sourced', '', '', '', '100%', 'Dave Francione', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 0, 0, 'Standard Margine Pipeline - Non-Corporate', '', '', ''),
(131, '', '9/8/2014', '', '', '', 'Pre Market', '', '', '', '', NULL, 'Rick deNey', 'TMT', 'Technology/Media/Telecom - Tech - Software', '', '', '', '', '', '', '', '', '', '', '', 'Sole Sourced', '', '', '', '100%', 'Rick deNey', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 0, 0, 'Standard Margine Pipeline - Non-Corporate', '', '', ''),
(132, '8/13/2014', '8/18/2014', '', 'Clearwater Systems Corporation', '', 'Pre Market', 'M&A - Sell-side', 'Minimum', '', '', NULL, 'Samrat Karnik', 'Industrials', 'Industrials - Technology - Controls, Instruments & Sensors', '$4,000,000', '', '', '$450,000', '450000', '', '', '', '10000', '', 'Privately Owned', '', '', '', '', '100%', 'Samrat Karnik', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 0, 0, 'Standard Margine Pipeline - Non-Corporate', '', '', ''),
(133, '10/13/2010', '10/2/2014', '', 'Creative Electronics Systems', '', '', '', '', '', '', NULL, 'Jerry Sturgill', '', 'Technology/Media/Telecom - Tech - Hardware', '', '', '', '', '', '', '', '', '', '', '', 'Sole Sourced', '', '', '', '100%', 'Jerry Sturgill', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 0, 0, 'Standard Margine Pipeline - Non-Corporate', '', '', ''),
(134, '', '8/18/2014', '', '', '', 'Pre Market', '', '', '', '', NULL, 'CJ Hummel', 'Energy & Natural Resources', 'Energy & Natural Resources - Pipeline', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '100%', 'CJ Hummel', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 0, 0, 'Standard Margine Pipeline - Non-Corporate', '', '', ''),
(135, '10/6/2014', '10/2/2014', '', 'Project Black Tie', '', 'In Market', 'M&A - Sell-side', 'Minimum', '', '', NULL, 'Tyler Comann', 'Business Services', 'Business Services - Distribution, Transportation & Logistics', '', '', '', '$200,000', '150000', '', '', '', '15000', '', 'Privately Owned', 'Corporate to Practice', '', '', '', '100%', 'Tyler Comann', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 0, 0, 'Standard Margine Pipeline - Non-Corporate', '', '', ''),
(136, '10/2/2014', '9/30/2014', '', 'DPRA', '', 'Pre Market', 'M&A - Sell-side', 'Wheelhouse', '', '', NULL, 'David Brinkley', 'Industrials', 'Industrials - Aerospace/Defense', '$12,000,000', '$10mm - $25mm', '', '$550,000', '500000', '', '', '', '15000', '', 'Privately Owned', 'Sole Sourced', '', '', '', '100%', 'David Brinkley', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 0, 0, 'Standard Margine Pipeline - Non-Corporate', '', '', ''),
(137, '9/10/2014', '9/8/2014', '12/14/2014', 'Dyersdale Energy LP', '', 'In Market', 'M&A - Sell-side,Divestiture', 'Wheelhouse', '', '', NULL, 'Macy/Pietravalle', 'Energy & Natural Resources', 'Energy & Natural Resources - Oil & Gas - E&P', '$35,000,000', '$25mm - $75mm', '', '$500,000', '', '', '', '', '10000', '', 'Privately Owned', 'Practice to Practice', '', '', '', '100%', 'Macy/Pietravalle', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 0, 0, 'Standard Margine Pipeline - Non-Corporate', '', '', ''),
(138, '', '8/18/2014', '', 'Elbit Kinetics', '', 'Pre Market', '', '', '', '', NULL, 'Tess Oxenstierna', 'Industrials', 'Industrials - Aerospace/Defense', '', '', '', '', '', '', '', '', '', '', '', 'Sole Sourced', '', '', '', '100%', 'Tess Oxenstierna', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 0, 0, 'Standard Margine Pipeline - Non-Corporate', '', '', ''),
(139, '8/27/2014', '8/18/2014', '', 'Energy C2', '', 'Pre Market', 'Capital Formation - Debt', 'Wheelhouse', '', '', NULL, 'Mike Swartz', 'Energy & Natural Resources', 'Energy & Natural Resources - Alternative - Solar', '$98,000,000', '$75mm - $100mm', '', '$3,275,000', '', '', '', '', '5000', '', 'Privately Owned', 'IBS to Practice', 'Energy C2', '', '', '50%', 'Mike Swartz', '50%', 'CJ Hummel', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 0, 0, 'Standard Margine Pipeline - Non-Corporate', '', '', ''),
(140, '', '8/25/2014', '', 'Environmental Tectonics Corp.', '', 'Pre Market', '', '', '', '', NULL, 'Tess Oxenstierna', 'Industrials', 'Industrials - Aerospace/Defense', '', '', '', '', '', '', '', '', '', '', '', 'Sole Sourced', '', '', '', '100%', 'Tess Oxenstierna', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 0, 0, 'Standard Margine Pipeline - Non-Corporate', '', '', ''),
(141, '9/30/2014', '8/29/2014', '', 'Kirusa', '', 'Pre Market', 'Capital Formation - Equity,M&A - Sell-side', 'Wheelhouse', '', '', NULL, 'Gary Moon', 'TMT', 'Technology/Media/Telecom - Tech - Software', '$30,000,000', '$25mm - $75mm', '', '$900,000', '500000', '', '', '', '10000', '', 'Privately Owned', 'Sole Sourced', '', '', '', '100%', 'Gary Moon', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 0, 0, 'Standard Margine Pipeline - Non-Corporate', '', '', ''),
(142, '9/17/2014', '', '', 'Project Stage Coach', '', 'In Market', 'M&A - Sell-side', 'Minimum', '', '', NULL, 'Tyler Comann', 'Business Services', 'Business Services - Distribution, Transportation & Logistics', '$10,000,000', '< $10mm', '', '$450,000', '300000', '', '', '', '7500', '', 'Privately Owned', 'Sole Sourced', '', '', '', '100%', 'Tyler Comann', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 0, 0, 'Standard Margine Pipeline - Non-Corporate', '', '', ''),
(143, '8/26/2014', '7/25/2014', '', 'Timer', '', 'Pre Market', 'M&A - Buy-side', 'Speculative', '', '', NULL, 'Len LaPorta', 'Industrials', 'Industrials - Aerospace/Defense', '', '', '', '$400,000', '400000', '15000', '', '', '15000', '', 'Privately Owned', 'SC to Practice', 'Headwaters SC', '', '', '100%', 'Len LaPorta', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 0, 0, 'Standard Margine Pipeline - Non-Corporate', '', '', ''),
(144, '7/21/2014', '7/16/2014', '', 'Project Grizzly', '', 'Pre Market', 'Capital Formation - Debt,Capital Formation - Equity', 'Wheelhouse', '', '', NULL, 'Macy/Pietravalle', 'Energy & Natural Resources', 'Energy & Natural Resources - Oil & Gas - E&P', '$50,000,000', '$25mm - $75mm', '', '$1,500,000', '450000', '20000', '', '', '10000', '', 'Privately Owned', 'IBS to Practice', 'Pacific Operators Offshore', '', '', '100%', 'Macy/Pietravalle', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 0, 0, 'Standard Margine Pipeline - Non-Corporate', '', '', ''),
(145, '9/24/2014', '9/29/2014', '', 'PAREX USA', '', 'In Market', 'M&A - Buy-side', 'Minimum', '', '', NULL, 'Grant Garbers', 'Industrials', 'Industrials - Building Products & Construction Services', '$15,000,000', '$10mm - $25mm', '', '$275,000', '450000', '50000', '', '', '', '', 'Privately Owned', 'Sole Sourced', '', '', '', '50%', 'Grant Garbers', '50%', 'Peter Nam', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 0, 0, 'Standard Margine Pipeline - Non-Corporate', '', '', ''),
(146, '9/12/2014', '8/18/2014', '', 'Project Quiet', '', 'Pre Market', 'M&A - Sell-side', 'Wheelhouse', '', '', NULL, 'Rick deNey', 'Industrials', 'Industrials - Technology', '$25,000,000', '$10mm - $25mm', '', '$625,000', '250000', '50000', '', '', '', '', 'Privately Owned', 'IBS to Practice', 'Silescent Lighting Corp.', '', '', '100%', 'Rick deNey', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 0, 0, 'Standard Margine Pipeline - Non-Corporate', '', '', ''),
(147, '8/25/2014', '8/18/2014', '', 'SpiralEdge', '', 'Pre Market', 'M&A - Sell-side', 'Wheelhouse', '', '', NULL, 'Gary Moon', 'TMT', 'Technology/Media/Telecom - Other', '$80,000,000', '$75mm - $100mm', '', '$1,000,000', '800000', '', '', '', '15000', '', 'Privately Owned', 'IBS to Practice', 'SpiralEdge', '', '', '100%', 'Gary Moon', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 0, 0, 'Standard Margine Pipeline - Non-Corporate', '', '', ''),
(148, '9/30/2014', '9/22/2014', '', 'Tellagence', '', 'Pre Market', 'M&A - Sell-side', 'Speculative', '', '', NULL, 'Sun Jen Yung', 'TMT', 'Technology/Media/Telecom - Media - Internet Media and Marketing', '$15,000,000', '$10mm - $25mm', '', '$500,000', '', '', '', '', '10000', '', 'Privately Owned', 'Sole Sourced', '', '', '', '100%', 'Sun Jen Yung', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 0, 0, 'Standard Margine Pipeline - Non-Corporate', '', '', ''),
(149, 'test', '10/1/2014', '`11/2/2014', '1/1/2015', NULL, '1/1/2015', 'Open', 'test', 'test', '1/1/2015', '1/6/2014', 'test', 'test', 'test', 'test', 'test', 'test', 'test', 'test', 'test', 'test', 'test', 'test', 'test', 'test', 'test', 'test', 'test', 'test', 'test', 'test', 'test', 'test', 'test', 'test', 'test', 'test', 'test', 'test', 'test', 'test', 'test', 'test', 'test', 'test', 'test', 'test', 'test', 'test', 'test', 'test', 'test', 'test', 1, 1, 'test', 'test', 'test', 'test');

--
-- Indexes for dumped tables
--

--
-- Indexes for table `company`
--
ALTER TABLE `company`
 ADD PRIMARY KEY (`ID`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `company`
--
ALTER TABLE `company`
MODIFY `ID` int(11) NOT NULL AUTO_INCREMENT,AUTO_INCREMENT=150;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
